scoreboard players add @s SRcd 1
execute @s[score_SRcd_min=20,score_SRcd=20] ~ ~ ~ tellraw @a[score_gSA_min=1,score_gSA=1] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"SR","color":"gray","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Slow Race","color":"gray"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 720573389"}},{"text":"]","color":"gray"},{"text":": "},{"text":"5","color":"yellow","bold":"true"}]}
execute @s[score_SRcd_min=20,score_SRcd=20] ~ ~ ~ execute @a[score_gSA_min=1,score_gSA=1] ~ ~ ~ playsound minecraft:block.note.pling voice @a[c=1] ~ ~ ~ 0.5
execute @s[score_SRcd_min=40,score_SRcd=40] ~ ~ ~ tellraw @a[score_gSA_min=1,score_gSA=1] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"SR","color":"gray","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Slow Race","color":"gray"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 720573389"}},{"text":"]","color":"gray"},{"text":": "},{"text":"4","color":"yellow","bold":"true"}]}
execute @s[score_SRcd_min=40,score_SRcd=40] ~ ~ ~ execute @a[score_gSA_min=1,score_gSA=1] ~ ~ ~ playsound minecraft:block.note.pling voice @a[c=1] ~ ~ ~ 1
execute @s[score_SRcd_min=60,score_SRcd=60] ~ ~ ~ tellraw @a[score_gSA_min=1,score_gSA=1] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"SR","color":"gray","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Slow Race","color":"gray"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 720573389"}},{"text":"]","color":"gray"},{"text":": "},{"text":"3","color":"yellow","bold":"true"}]}
execute @s[score_SRcd_min=60,score_SRcd=60] ~ ~ ~ execute @a[score_gSA_min=1,score_gSA=1] ~ ~ ~ playsound minecraft:block.note.pling voice @a[c=1] ~ ~ ~ 1.5
execute @s[score_SRcd_min=80,score_SRcd=80] ~ ~ ~ tellraw @a[score_gSA_min=1,score_gSA=1] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"SR","color":"gray","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Slow Race","color":"gray"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 720573389"}},{"text":"]","color":"gray"},{"text":": "},{"text":"2","color":"yellow","bold":"true"}]}
execute @s[score_SRcd_min=80,score_SRcd=80] ~ ~ ~ execute @a[score_gSA_min=1,score_gSA=1] ~ ~ ~ playsound minecraft:block.note.pling voice @a[c=1] ~ ~ ~ 2
execute @s[score_SRcd_min=100,score_SRcd=100] ~ ~ ~ tellraw @a[score_gSA_min=1,score_gSA=1] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"SR","color":"gray","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Slow Race","color":"gray"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 720573389"}},{"text":"]","color":"gray"},{"text":": "},{"text":"1","color":"yellow","bold":"true"}]}
execute @s[score_SRcd_min=100,score_SRcd=100] ~ ~ ~ execute @a[score_gSA_min=1,score_gSA=1] ~ ~ ~ playsound minecraft:block.note.pling voice @a[c=1] ~ ~ ~ 2
execute @s[score_SRcd_min=120,score_SRcd=120] ~ ~ ~ execute @a[score_gSA_min=1,score_gSA=1] ~ ~ ~ playsound minecraft:entity.wither.death voice @a[c=1]
execute @s[score_SRcd_min=120,score_SRcd=120] ~ ~ ~ tellraw @a[score_gSA_min=1,score_gSA=1] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"SR","color":"gray","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Slow Race","color":"gray"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 720573389"}},{"text":"]","color":"gray"},{"text":": "},{"text":"GO!","color":"green","bold":"true"}]}
execute @s[score_SRcd_min=120,score_SRcd=120] ~ ~ ~ title @a[score_gSA_min=1,score_gSA=1] title {"text":"GO!","color":"green"}
execute @s[score_SRcd_min=120,score_SRcd=120] ~ ~ ~ fill 71 5 -82 71 5 -78 stonebrick 0 replace redstone_block 0
