minecraft:tp @s[score_FLtp_min=803738518,score_FLtp=803738518] 49 36 -45 -90 0
tellraw @s[score_FLtp_min=803738518,score_FLtp=803738518] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 69110609"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"49 36 -45","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Ice race","color":"aqua","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Ice race","color":"aqua"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 803738518"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=720573389,score_FLtp=720573389] 75 7 -80 90 0
tellraw @s[score_FLtp_min=720573389,score_FLtp=720573389] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 69110609"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"75 7 -80","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Slow Race","color":"gray","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Slow Race","color":"gray"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 720573389"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=1061722156,score_FLtp=1061722156] 73 7 -102 90 0
tellraw @s[score_FLtp_min=1061722156,score_FLtp=1061722156] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 69110609"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"73 7 -102","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Nether Race","color":"red","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Nether Race","color":"red"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1061722156"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=840715523,score_FLtp=840715523] 23 7 -133 -90 0
tellraw @s[score_FLtp_min=840715523,score_FLtp=840715523] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 69110609"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"23 7 -133","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Evil Race","color":"gray","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Evil Race","color":"gray"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 840715523"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=878514327,score_FLtp=878514327] 218 18 -37 -90 0
tellraw @s[score_FLtp_min=878514327,score_FLtp=878514327] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 69110609"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"218 18 -37","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Diamond Race","color":"aqua","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Diamond Race","color":"aqua"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 878514327"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=1844105133,score_FLtp=1844105133] 276 17 -96 90 0
tellraw @s[score_FLtp_min=1844105133,score_FLtp=1844105133] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 69110609"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"276 17 -96","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Emerald Race","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Emerald Race","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1844105133"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=1964796834,score_FLtp=1964796834] 229 8 -157 -90 0
tellraw @s[score_FLtp_min=1964796834,score_FLtp=1964796834] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 69110609"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"229 8 -157","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Quartz Race","color":"white","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Quartz Race","color":"white"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1964796834"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=1372444959,score_FLtp=1372444959] 242 26 -222 -90 0
tellraw @s[score_FLtp_min=1372444959,score_FLtp=1372444959] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 69110609"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"242 26 -222","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"1.8 Race","color":"gold","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"1.8 Race","color":"gold"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1372444959"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=165517204,score_FLtp=165517204] 424 12 -122 -90 0
tellraw @s[score_FLtp_min=165517204,score_FLtp=165517204] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 69110609"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"424 12 -122","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Epic Race","color":"gold","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Epic Race","color":"gold"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 165517204"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=942958520,score_FLtp=942958520] 467 8 -33 -90 0
tellraw @s[score_FLtp_min=942958520,score_FLtp=942958520] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 69110609"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"467 8 -33","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Salt Race","color":"gray","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Salt Race","color":"gray"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 942958520"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=54328140,score_FLtp=54328140] 31 20 -240 -45 0
tellraw @s[score_FLtp_min=54328140,score_FLtp=54328140] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 69110609"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"31 20 -240","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Death Run","color":"red","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Death Run","color":"red"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 54328140"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=2140645621,score_FLtp=2140645621] 23 15 -189.0 -90 0
tellraw @s[score_FLtp_min=2140645621,score_FLtp=2140645621] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 69110609"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"23 15 -189","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Dirt Race","color":"gray","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Dirt Race","color":"gray"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 2140645621"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=767278703,score_FLtp=767278703] 445 68 -669.0 -90 0
tellraw @s[score_FLtp_min=767278703,score_FLtp=767278703] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 69110609"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"445 68 -669","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Mycelium Race","color":"dark_purple","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Mycelium Race","color":"dark_purple"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 767278703"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=1848527163,score_FLtp=1848527163] 517 11 -827 90 0
tellraw @s[score_FLtp_min=1848527163,score_FLtp=1848527163] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 69110609"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"517 11 -827","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Frostburn Run","color":"aqua","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Frostburn Run","color":"aqua"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1848527163"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=972907871,score_FLtp=972907871] 460 3 -331 -90 0
tellraw @s[score_FLtp_min=972907871,score_FLtp=972907871] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 69110609"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"460 3 -331","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"EverChanging Race","color":"yellow","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"EverChanging Race","color":"yellow"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 972907871"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=1095056157,score_FLtp=1095056157] -85 45 -241 -45 0
tellraw @s[score_FLtp_min=1095056157,score_FLtp=1095056157] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 69110609"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"-85 45 -241","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Virus 1","color":"yellow","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Virus 1","color":"yellow"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1095056157"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=763826195,score_FLtp=763826195] -77 56 -85 -45 0
tellraw @s[score_FLtp_min=763826195,score_FLtp=763826195] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 69110609"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"-77 56 -85","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Virus 2","color":"yellow","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Virus 2","color":"yellow"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 763826195"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=1228762126,score_FLtp=1228762126] -268 49 -39 -90 0
tellraw @s[score_FLtp_min=1228762126,score_FLtp=1228762126] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 69110609"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"-268 49 -39","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"PVP: Old CTF","color":"red","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"PVP: Old CTF","color":"red"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1228762126"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=539017757,score_FLtp=539017757] 558 107 159.0 90 0
tellraw @s[score_FLtp_min=539017757,score_FLtp=539017757] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 69110609"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"558 107 159","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Capture","color":"red","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Capture the flag","color":"red"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 539017757"}},{"text":" the ","color":"white","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Capture the flag","color":"white"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 539017757"}},{"text":"flag","color":"blue","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Capture the flag","color":"blue"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 539017757"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=586508005,score_FLtp=586508005] -105 25 200 -135 0
tellraw @s[score_FLtp_min=586508005,score_FLtp=586508005] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 69110609"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"-105 25 200","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"The Pit 3","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"The Pit 3","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 586508005"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=1368311757,score_FLtp=1368311757] -250 25 18 -90 0
tellraw @s[score_FLtp_min=1368311757,score_FLtp=1368311757] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 69110609"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"-250 25 18","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Sand Tomb","color":"yellow","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Sand Tomb","color":"yellow"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1368311757"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=333805818,score_FLtp=333805818] -16 5 87 90 0
tellraw @s[score_FLtp_min=333805818,score_FLtp=333805818] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 69110609"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"-16 5 87","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Anvil Drop","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Anvil Drop","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 333805818"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=1978548874,score_FLtp=1978548874] -187 24 96 -90 0
tellraw @s[score_FLtp_min=1978548874,score_FLtp=1978548874] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 69110609"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"-187 24 96","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Death Pit","color":"red","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Death Pit","color":"red"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1978548874"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=726964523,score_FLtp=726964523] 214 27 334 -90 0
tellraw @s[score_FLtp_min=726964523,score_FLtp=726964523] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 69110609"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"214 27 334","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Rabbit","color":"red","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Rabbit Ball","color":"red"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 726964523"}},{"text":" ","color":"white","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Rabbit Ball","color":"white"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 726964523"}},{"text":"Ball","color":"blue","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Rabbit Ball","color":"blue"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 726964523"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=1217546713,score_FLtp=1217546713] 77 5 41 0 -15
tellraw @s[score_FLtp_min=1217546713,score_FLtp=1217546713] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 69110609"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"77 5 41","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Mastermind","color":"gold","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Mastermind","color":"gold"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1217546713"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=1301307747,score_FLtp=1301307747] 161 4 180 90 0
tellraw @s[score_FLtp_min=1301307747,score_FLtp=1301307747] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 69110609"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"161 4 180","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"P","color":"light_purple","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Pictionary","color":"light_purple"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1301307747"}},{"text":"i","color":"red","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Pictionary","color":"red"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1301307747"}},{"text":"c","color":"gold","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Pictionary","color":"gold"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1301307747"}},{"text":"t","color":"yellow","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Pictionary","color":"yellow"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1301307747"}},{"text":"i","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Pictionary","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1301307747"}},{"text":"o","color":"dark_green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Pictionary","color":"dark_green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1301307747"}},{"text":"n","color":"blue","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Pictionary","color":"blue"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1301307747"}},{"text":"a","color":"dark_aqua","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Pictionary","color":"dark_aqua"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1301307747"}},{"text":"r","color":"aqua","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Pictionary","color":"aqua"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1301307747"}},{"text":"y","color":"white","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Pictionary","color":"white"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1301307747"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=1336970968,score_FLtp=1336970968] -103 19 482 -180 0
tellraw @s[score_FLtp_min=1336970968,score_FLtp=1336970968] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 69110609"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"-103 19 482","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Royal","color":"blue","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Royal Rumble","color":"blue"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1336970968"}},{"text":" ","color":"white","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Royal Rumble","color":"white"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1336970968"}},{"text":"Rumble","color":"dark_green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Royal Rumble","color":"dark_green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1336970968"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=244577678,score_FLtp=244577678] -1439 12 -228 90 0
tellraw @s[score_FLtp_min=244577678,score_FLtp=244577678] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 69110609"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"-1439 12 -228","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"A Small Village","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"A Small Village","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 244577678"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=1203107457,score_FLtp=1203107457] -1530 45 -50
tellraw @s[score_FLtp_min=1203107457,score_FLtp=1203107457] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 69110609"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"-1530 45 -50","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Apocalypse","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Apocalypse","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1203107457"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=606156446,score_FLtp=606156446] -1607 64 -60 90 0
tellraw @s[score_FLtp_min=606156446,score_FLtp=606156446] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 69110609"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"-1607 64 -60","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Castle de Emmy","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Castle de Emmy","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 606156446"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=526354106,score_FLtp=526354106] -1313 102 -241 0 0
tellraw @s[score_FLtp_min=526354106,score_FLtp=526354106] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 69110609"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"-1313 102 -241","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Four Corners","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Four Corners","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 526354106"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=478919104,score_FLtp=478919104] -1107 24 -35 -90 0
tellraw @s[score_FLtp_min=478919104,score_FLtp=478919104] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 69110609"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"-1107 24 -35","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"HASDaa","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"HASDaa","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 478919104"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=1159673785,score_FLtp=1159673785] -1073 26 -277 90 0
tellraw @s[score_FLtp_min=1159673785,score_FLtp=1159673785] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 69110609"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"-1073 26 -277","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Hospital","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Hospital","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1159673785"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=184603297,score_FLtp=184603297] -1106 10 -97 180 0
tellraw @s[score_FLtp_min=184603297,score_FLtp=184603297] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 69110609"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"-1106 10 -97","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Jungle","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Jungle","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 184603297"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=498683800,score_FLtp=498683800] -1175 46 -264
tellraw @s[score_FLtp_min=498683800,score_FLtp=498683800] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 69110609"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"-1175 46 -264","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Mastermind","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Mastermind","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 498683800"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=607841732,score_FLtp=607841732] -1081 43 -189 180 0
tellraw @s[score_FLtp_min=607841732,score_FLtp=607841732] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 69110609"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"-1081 43 -189","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Mushroom Village","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Mushroom Village","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 607841732"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=354536009,score_FLtp=354536009] -1158 44 -139 180 0
tellraw @s[score_FLtp_min=354536009,score_FLtp=354536009] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 69110609"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"-1158 44 -139","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Old","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Old","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 354536009"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=818788035,score_FLtp=818788035] -1242 37 -246 0 0
tellraw @s[score_FLtp_min=818788035,score_FLtp=818788035] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 69110609"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"-1242 37 -246","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Park","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Park","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 818788035"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=658982564,score_FLtp=658982564] -1153 27 -69 -180 0
tellraw @s[score_FLtp_min=658982564,score_FLtp=658982564] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 69110609"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"-1153 27 -69","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Rainbow","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Rainbow","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 658982564"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=1456309508,score_FLtp=1456309508] -1430 98 -46 0 0
tellraw @s[score_FLtp_min=1456309508,score_FLtp=1456309508] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 69110609"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"-1430 98 -46","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Resort","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Resort","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1456309508"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=993875352,score_FLtp=993875352] -1252 32 -88
tellraw @s[score_FLtp_min=993875352,score_FLtp=993875352] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 69110609"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"-1252 32 -88","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Train Station","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Train Station","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 993875352"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=1387594773,score_FLtp=1387594773] -85 45 -241 -45 0
tellraw @s[score_FLtp_min=1387594773,score_FLtp=1387594773] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 69110609"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"-85 45 -241","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"BH Virus 1","color":"yellow","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"BH Virus 1","color":"yellow"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1387594773"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=1478269764,score_FLtp=1478269764] -77 56 -85 -45 0
tellraw @s[score_FLtp_min=1478269764,score_FLtp=1478269764] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 69110609"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"-77 56 -85","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"BH Virus 2","color":"yellow","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"BH Virus 2","color":"yellow"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1478269764"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=558233482,score_FLtp=558233482] -1168 32 -191 -180 0
tellraw @s[score_FLtp_min=558233482,score_FLtp=558233482] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 69110609"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"-1168 32 -191","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Zelda","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Zelda","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 558233482"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=1360624640,score_FLtp=1360624640] 397 17 61 90 0
tellraw @s[score_FLtp_min=1360624640,score_FLtp=1360624640] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 69110609"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"397 17 61","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Spawn","color":"dark_red","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Spawn","color":"dark_red"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1360624640"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=69110609,score_FLtp=69110609] 348 4 114 -90 0
tellraw @s[score_FLtp_min=69110609,score_FLtp=69110609] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 69110609"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"348 4 114","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Floo Network","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 69110609"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=2052427056,score_FLtp=2052427056] 549 20 42
tellraw @s[score_FLtp_min=2052427056,score_FLtp=2052427056] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 69110609"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"549 20 42","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Teamspeak Token","color":"dark_aqua","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Teamspeak Token","color":"dark_aqua"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 2052427056"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=589803134,score_FLtp=589803134] 329 24.065 171 90 0
tellraw @s[score_FLtp_min=589803134,score_FLtp=589803134] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 69110609"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"329 24 171","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"The Minigame Hub","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"The Minigame Hub","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 589803134"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=1585275904,score_FLtp=1585275904] 385 15 159 180 0
tellraw @s[score_FLtp_min=1585275904,score_FLtp=1585275904] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 69110609"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"385 15 159","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"The PVP hub","color":"light_purple","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"The PVP hub","color":"light_purple"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1585275904"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=148613941,score_FLtp=148613941] 329 24.065 154 90 0
tellraw @s[score_FLtp_min=148613941,score_FLtp=148613941] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 69110609"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"329 24 154","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"The Mastermind Hub","color":"gold","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"The Mastermind Hub","color":"gold"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 148613941"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=1959278767,score_FLtp=1959278767] 329 24.076 137 90 0
tellraw @s[score_FLtp_min=1959278767,score_FLtp=1959278767] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 69110609"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"329 24 137","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"The Race Hub","color":"dark_aqua","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"The Race Hub","color":"dark_aqua"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1959278767"}},{"text":"!","color":"gray"}]}
execute @s ~ ~ ~ playsound minecraft:entity.experience_orb.pickup voice @s
scoreboard players set @s FLtp 0
