minecraft:tp @s[score_FLtp_min=227577150,score_FLtp=227577150] 49 36 -45 -90 0
tellraw @s[score_FLtp_min=227577150,score_FLtp=227577150] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 674271822"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"49 36 -45","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Ice race","color":"aqua","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Ice race","color":"aqua"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 227577150"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=1639073828,score_FLtp=1639073828] 75 7 -80 90 0
tellraw @s[score_FLtp_min=1639073828,score_FLtp=1639073828] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 674271822"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"75 7 -80","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Slow Race","color":"gray","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Slow Race","color":"gray"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1639073828"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=1411077721,score_FLtp=1411077721] 73 7 -102 90 0
tellraw @s[score_FLtp_min=1411077721,score_FLtp=1411077721] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 674271822"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"73 7 -102","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Nether Race","color":"red","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Nether Race","color":"red"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1411077721"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=1441799265,score_FLtp=1441799265] 23 7 -133 -90 0
tellraw @s[score_FLtp_min=1441799265,score_FLtp=1441799265] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 674271822"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"23 7 -133","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Evil Race","color":"gray","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Evil Race","color":"gray"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1441799265"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=284291924,score_FLtp=284291924] 218 18 -37 -90 0
tellraw @s[score_FLtp_min=284291924,score_FLtp=284291924] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 674271822"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"218 18 -37","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Diamond Race","color":"aqua","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Diamond Race","color":"aqua"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 284291924"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=704022040,score_FLtp=704022040] 276 17 -96 90 0
tellraw @s[score_FLtp_min=704022040,score_FLtp=704022040] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 674271822"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"276 17 -96","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Emerald Race","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Emerald Race","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 704022040"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=1336477430,score_FLtp=1336477430] 229 8 -157 -90 0
tellraw @s[score_FLtp_min=1336477430,score_FLtp=1336477430] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 674271822"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"229 8 -157","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Quartz Race","color":"white","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Quartz Race","color":"white"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1336477430"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=244076999,score_FLtp=244076999] 242 26 -222 -90 0
tellraw @s[score_FLtp_min=244076999,score_FLtp=244076999] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 674271822"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"242 26 -222","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"1.8 Race","color":"gold","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"1.8 Race","color":"gold"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 244076999"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=929476859,score_FLtp=929476859] 424 12 -122 -90 0
tellraw @s[score_FLtp_min=929476859,score_FLtp=929476859] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 674271822"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"424 12 -122","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Epic Race","color":"gold","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Epic Race","color":"gold"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 929476859"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=1290793335,score_FLtp=1290793335] 467 8 -33 -90 0
tellraw @s[score_FLtp_min=1290793335,score_FLtp=1290793335] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 674271822"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"467 8 -33","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Salt Race","color":"gray","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Salt Race","color":"gray"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1290793335"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=1625759596,score_FLtp=1625759596] 31 20 -240 -45 0
tellraw @s[score_FLtp_min=1625759596,score_FLtp=1625759596] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 674271822"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"31 20 -240","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Death Run","color":"red","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Death Run","color":"red"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1625759596"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=697385017,score_FLtp=697385017] 23 15 -189.0 -90 0
tellraw @s[score_FLtp_min=697385017,score_FLtp=697385017] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 674271822"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"23 15 -189","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Dirt Race","color":"gray","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Dirt Race","color":"gray"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 697385017"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=2083967759,score_FLtp=2083967759] 445 68 -669.0 -90 0
tellraw @s[score_FLtp_min=2083967759,score_FLtp=2083967759] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 674271822"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"445 68 -669","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Mycelium Race","color":"dark_purple","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Mycelium Race","color":"dark_purple"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 2083967759"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=1689433145,score_FLtp=1689433145] 517 11 -827 90 0
tellraw @s[score_FLtp_min=1689433145,score_FLtp=1689433145] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 674271822"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"517 11 -827","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Frostburn Run","color":"aqua","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Frostburn Run","color":"aqua"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1689433145"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=1390739026,score_FLtp=1390739026] 460 3 -331 -90 0
tellraw @s[score_FLtp_min=1390739026,score_FLtp=1390739026] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 674271822"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"460 3 -331","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"EverChanging Race","color":"yellow","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"EverChanging Race","color":"yellow"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1390739026"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=1561350378,score_FLtp=1561350378] -85 45 -241 -45 0
tellraw @s[score_FLtp_min=1561350378,score_FLtp=1561350378] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 674271822"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"-85 45 -241","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Virus 1","color":"yellow","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Virus 1","color":"yellow"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1561350378"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=1561350379,score_FLtp=1561350379] -77 56 -85 -45 0
tellraw @s[score_FLtp_min=1561350379,score_FLtp=1561350379] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 674271822"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"-77 56 -85","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Virus 2","color":"yellow","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Virus 2","color":"yellow"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1561350379"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=1773738438,score_FLtp=1773738438] -268 49 -39 -90 0
tellraw @s[score_FLtp_min=1773738438,score_FLtp=1773738438] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 674271822"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"-268 49 -39","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"PVP: Old CTF","color":"red","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"PVP: Old CTF","color":"red"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1773738438"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=1463087182,score_FLtp=1463087182] 558 107 159.0 90 0
tellraw @s[score_FLtp_min=1463087182,score_FLtp=1463087182] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 674271822"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"558 107 159","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Capture","color":"red","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Capture the flag","color":"red"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1463087182"}},{"text":" the ","color":"white","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Capture the flag","color":"white"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1463087182"}},{"text":"flag","color":"blue","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Capture the flag","color":"blue"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1463087182"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=1541518973,score_FLtp=1541518973] -105 25 200 -135 0
tellraw @s[score_FLtp_min=1541518973,score_FLtp=1541518973] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 674271822"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"-105 25 200","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"The Pit 3","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"The Pit 3","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1541518973"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=1100166785,score_FLtp=1100166785] -250 25 18 -90 0
tellraw @s[score_FLtp_min=1100166785,score_FLtp=1100166785] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 674271822"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"-250 25 18","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Sand Tomb","color":"yellow","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Sand Tomb","color":"yellow"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1100166785"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=637350197,score_FLtp=637350197] -16 5 87 90 0
tellraw @s[score_FLtp_min=637350197,score_FLtp=637350197] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 674271822"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"-16 5 87","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Anvil Drop","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Anvil Drop","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 637350197"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=1625757028,score_FLtp=1625757028] -187 24 96 -90 0
tellraw @s[score_FLtp_min=1625757028,score_FLtp=1625757028] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 674271822"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"-187 24 96","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Death Pit","color":"red","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Death Pit","color":"red"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1625757028"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=1299512154,score_FLtp=1299512154] 214 27 334 -90 0
tellraw @s[score_FLtp_min=1299512154,score_FLtp=1299512154] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 674271822"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"214 27 334","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Rabbit","color":"red","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Rabbit Ball","color":"red"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1299512154"}},{"text":" ","color":"white","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Rabbit Ball","color":"white"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1299512154"}},{"text":"Ball","color":"blue","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Rabbit Ball","color":"blue"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1299512154"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=1807172851,score_FLtp=1807172851] 77 5 41 0 -15
tellraw @s[score_FLtp_min=1807172851,score_FLtp=1807172851] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 674271822"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"77 5 41","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Mastermind","color":"gold","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Mastermind","color":"gold"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1807172851"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=1511200574,score_FLtp=1511200574] 161 4 180 90 0
tellraw @s[score_FLtp_min=1511200574,score_FLtp=1511200574] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 674271822"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"161 4 180","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"P","color":"light_purple","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Pictionary","color":"light_purple"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1511200574"}},{"text":"i","color":"red","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Pictionary","color":"red"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1511200574"}},{"text":"c","color":"gold","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Pictionary","color":"gold"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1511200574"}},{"text":"t","color":"yellow","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Pictionary","color":"yellow"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1511200574"}},{"text":"i","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Pictionary","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1511200574"}},{"text":"o","color":"dark_green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Pictionary","color":"dark_green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1511200574"}},{"text":"n","color":"blue","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Pictionary","color":"blue"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1511200574"}},{"text":"a","color":"dark_aqua","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Pictionary","color":"dark_aqua"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1511200574"}},{"text":"r","color":"aqua","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Pictionary","color":"aqua"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1511200574"}},{"text":"y","color":"white","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Pictionary","color":"white"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1511200574"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=1698782159,score_FLtp=1698782159] -103 19 482 -180 0
tellraw @s[score_FLtp_min=1698782159,score_FLtp=1698782159] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 674271822"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"-103 19 482","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Royal","color":"blue","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Royal Rumble","color":"blue"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1698782159"}},{"text":" ","color":"white","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Royal Rumble","color":"white"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1698782159"}},{"text":"Rumble","color":"dark_green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Royal Rumble","color":"dark_green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1698782159"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=1299512154,score_FLtp=1299512154] 224 24 334 -90 0
tellraw @s[score_FLtp_min=1299512154,score_FLtp=1299512154] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 674271822"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"224 24 334","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Rabbit","color":"red","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Rabbit Ball","color":"red"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1299512154"}},{"text":" ","color":"white","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Rabbit Ball","color":"white"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1299512154"}},{"text":"Ball","color":"blue","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Rabbit Ball","color":"blue"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1299512154"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=236718384,score_FLtp=236718384] 397 17 61 90 0
tellraw @s[score_FLtp_min=236718384,score_FLtp=236718384] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 674271822"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"397 17 61","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Spawn","color":"dark_red","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Spawn","color":"dark_red"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 236718384"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=674271822,score_FLtp=674271822] 348 4 114 -90 0
tellraw @s[score_FLtp_min=674271822,score_FLtp=674271822] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 674271822"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"348 4 114","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Floo Network","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 674271822"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=1971168489,score_FLtp=1971168489] 549 20 42
tellraw @s[score_FLtp_min=1971168489,score_FLtp=1971168489] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 674271822"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"549 20 42","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"Teamspeak Token","color":"dark_aqua","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Teamspeak Token","color":"dark_aqua"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1971168489"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=327765745,score_FLtp=327765745] 329 24.065 171 90 0
tellraw @s[score_FLtp_min=327765745,score_FLtp=327765745] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 674271822"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"329 24 171","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"The Minigame Hub","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"The Minigame Hub","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 327765745"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=743229343,score_FLtp=743229343] 385 15 159 180 0
tellraw @s[score_FLtp_min=743229343,score_FLtp=743229343] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 674271822"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"385 15 159","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"The PVP hub","color":"light_purple","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"The PVP hub","color":"light_purple"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 743229343"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=81055981,score_FLtp=81055981] 329 24.065 154 90 0
tellraw @s[score_FLtp_min=81055981,score_FLtp=81055981] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 674271822"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"329 24 154","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"The Mastermind Hub","color":"gold","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"The Mastermind Hub","color":"gold"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 81055981"}},{"text":"!","color":"gray"}]}
minecraft:tp @s[score_FLtp_min=238315678,score_FLtp=238315678] 329 24.076 137 90 0
tellraw @s[score_FLtp_min=238315678,score_FLtp=238315678] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"Floo","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Floo Network","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 674271822"}},{"text":"]","color":"gray"},{"text":": "},{"text":"You have been teleported to ","color":"gray"},{"text":"329 24 137","color":"yellow","bold":"true"},{"text":" at ","color":"gray"},{"text":"The Race Hub","color":"dark_aqua","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"The Race Hub","color":"dark_aqua"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 238315678"}},{"text":"!","color":"gray"}]}
playsound minecraft:entity.experience_orb.pickup voice @s
scoreboard players operation @s FLtp *= -1 constants
