execute @s[score_BHOti_min=6000,score_BHOti=6000] ~ ~ ~ tellraw @a {"text":"","extra":[{"text":"[","color":"gray"},{"text":"BHO","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"BHO","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 193451326"}},{"text":"]","color":"gray"},{"text":": "},{"text":"5 minutes remain!","color":"yellow"}]}
execute @s[score_BHOti_min=4800,score_BHOti=4800] ~ ~ ~ tellraw @a {"text":"","extra":[{"text":"[","color":"gray"},{"text":"BHO","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"BHO","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 193451326"}},{"text":"]","color":"gray"},{"text":": "},{"text":"4 minutes remain!","color":"yellow"}]}
execute @s[score_BHOti_min=3600,score_BHOti=3600] ~ ~ ~ tellraw @a {"text":"","extra":[{"text":"[","color":"gray"},{"text":"BHO","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"BHO","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 193451326"}},{"text":"]","color":"gray"},{"text":": "},{"text":"3 minutes remain!","color":"yellow"}]}
execute @s[score_BHOti_min=2400,score_BHOti=2400] ~ ~ ~ tellraw @a {"text":"","extra":[{"text":"[","color":"gray"},{"text":"BHO","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"BHO","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 193451326"}},{"text":"]","color":"gray"},{"text":": "},{"text":"2 minutes remain!","color":"yellow"}]}
execute @s[score_BHOti_min=1200,score_BHOti=1200] ~ ~ ~ tellraw @a {"text":"","extra":[{"text":"[","color":"gray"},{"text":"BHO","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"BHO","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 193451326"}},{"text":"]","color":"gray"},{"text":": "},{"text":"1 minute remains!","color":"yellow"}]}
execute @s[score_BHOti_min=600,score_BHOti=600] ~ ~ ~ tellraw @a {"text":"","extra":[{"text":"[","color":"gray"},{"text":"BHO","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"BHO","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 193451326"}},{"text":"]","color":"gray"},{"text":": "},{"text":"30 seconds remain!","color":"yellow"}]}
execute @s[score_BHOti_min=300,score_BHOti=300] ~ ~ ~ tellraw @a {"text":"","extra":[{"text":"[","color":"gray"},{"text":"BHO","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"BHO","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 193451326"}},{"text":"]","color":"gray"},{"text":": "},{"text":"15 seconds remain!","color":"yellow"}]}
execute @s[score_BHOti_min=100,score_BHOti=100] ~ ~ ~ tellraw @a {"text":"","extra":[{"text":"[","color":"gray"},{"text":"BHO","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"BHO","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 193451326"}},{"text":"]","color":"gray"},{"text":": "},{"text":"5!","color":"yellow"}]}
execute @s[score_BHOti_min=80,score_BHOti=80] ~ ~ ~ tellraw @a {"text":"","extra":[{"text":"[","color":"gray"},{"text":"BHO","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"BHO","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 193451326"}},{"text":"]","color":"gray"},{"text":": "},{"text":"4!","color":"yellow"}]}
execute @s[score_BHOti_min=60,score_BHOti=60] ~ ~ ~ tellraw @a {"text":"","extra":[{"text":"[","color":"gray"},{"text":"BHO","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"BHO","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 193451326"}},{"text":"]","color":"gray"},{"text":": "},{"text":"3!","color":"yellow"}]}
execute @s[score_BHOti_min=40,score_BHOti=40] ~ ~ ~ tellraw @a {"text":"","extra":[{"text":"[","color":"gray"},{"text":"BHO","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"BHO","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 193451326"}},{"text":"]","color":"gray"},{"text":": "},{"text":"2!","color":"yellow"}]}
execute @s[score_BHOti_min=20,score_BHOti=20] ~ ~ ~ tellraw @a {"text":"","extra":[{"text":"[","color":"gray"},{"text":"BHO","color":"green","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"BHO","color":"green"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 193451326"}},{"text":"]","color":"gray"},{"text":": "},{"text":"1!","color":"yellow"}]}
scoreboard players set @s[score_BHOti=0] BHOst 4
