scoreboard players set @s MMHcl 0
scoreboard players set @s[score_MMHign_min=1,score_MMHign=1,score_MMHgn_min=1,score_MMHgn=1] MMHcl 1
scoreboard players set @s[score_MMHign_min=2,score_MMHign=2,score_MMHgn_min=2,score_MMHgn=2] MMHcl 1
scoreboard players set @s[score_MMHign_min=3,score_MMHign=3,score_MMHgn_min=3,score_MMHgn=3] MMHcl 1
scoreboard players set @s[score_MMHign_min=4,score_MMHign=4,score_MMHgn_min=4,score_MMHgn=4] MMHcl 1
scoreboard players set @s[score_MMHign_min=5,score_MMHign=5,score_MMHgn_min=5,score_MMHgn=5] MMHcl 1
scoreboard players set @s[score_MMHign_min=6,score_MMHign=6,score_MMHgn_min=6,score_MMHgn=6] MMHcl 1
scoreboard players set @s[score_MMHign_min=7,score_MMHign=7,score_MMHgn_min=7,score_MMHgn=7] MMHcl 1
scoreboard players set @s[score_MMHign_min=8,score_MMHign=8,score_MMHgn_min=8,score_MMHgn=8] MMHcl 1
scoreboard players set @s[score_MMHign_min=9,score_MMHign=9,score_MMHgn_min=9,score_MMHgn=9] MMHcl 1
execute @s[score_MMHcl_min=0,score_MMHcl=0,score_MMHgn_min=1,score_MMHgn=1] ~ ~ ~ tellraw @a[score_MMHrn_min=2,score_MMHrn=2] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"MMH","color":"red","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Mastermind Hell","color":"red"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 525124045"}},{"text":"]","color":"gray"},{"text":": "},{"text":"Warning: ","color":"red","bold":"true"},{"text":"Please use guess 1.","color":"gold"}]}
execute @s[score_MMHcl_min=0,score_MMHcl=0,score_MMHgn_min=2,score_MMHgn=2] ~ ~ ~ tellraw @a[score_MMHrn_min=2,score_MMHrn=2] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"MMH","color":"red","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Mastermind Hell","color":"red"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 525124045"}},{"text":"]","color":"gray"},{"text":": "},{"text":"Warning: ","color":"red","bold":"true"},{"text":"Please use guess 2.","color":"gold"}]}
execute @s[score_MMHcl_min=0,score_MMHcl=0,score_MMHgn_min=3,score_MMHgn=3] ~ ~ ~ tellraw @a[score_MMHrn_min=2,score_MMHrn=2] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"MMH","color":"red","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Mastermind Hell","color":"red"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 525124045"}},{"text":"]","color":"gray"},{"text":": "},{"text":"Warning: ","color":"red","bold":"true"},{"text":"Please use guess 3.","color":"gold"}]}
execute @s[score_MMHcl_min=0,score_MMHcl=0,score_MMHgn_min=4,score_MMHgn=4] ~ ~ ~ tellraw @a[score_MMHrn_min=2,score_MMHrn=2] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"MMH","color":"red","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Mastermind Hell","color":"red"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 525124045"}},{"text":"]","color":"gray"},{"text":": "},{"text":"Warning: ","color":"red","bold":"true"},{"text":"Please use guess 4.","color":"gold"}]}
execute @s[score_MMHcl_min=0,score_MMHcl=0,score_MMHgn_min=5,score_MMHgn=5] ~ ~ ~ tellraw @a[score_MMHrn_min=2,score_MMHrn=2] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"MMH","color":"red","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Mastermind Hell","color":"red"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 525124045"}},{"text":"]","color":"gray"},{"text":": "},{"text":"Warning: ","color":"red","bold":"true"},{"text":"Please use guess 5.","color":"gold"}]}
execute @s[score_MMHcl_min=0,score_MMHcl=0,score_MMHgn_min=6,score_MMHgn=6] ~ ~ ~ tellraw @a[score_MMHrn_min=2,score_MMHrn=2] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"MMH","color":"red","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Mastermind Hell","color":"red"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 525124045"}},{"text":"]","color":"gray"},{"text":": "},{"text":"Warning: ","color":"red","bold":"true"},{"text":"Please use guess 6.","color":"gold"}]}
execute @s[score_MMHcl_min=0,score_MMHcl=0,score_MMHgn_min=7,score_MMHgn=7] ~ ~ ~ tellraw @a[score_MMHrn_min=2,score_MMHrn=2] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"MMH","color":"red","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Mastermind Hell","color":"red"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 525124045"}},{"text":"]","color":"gray"},{"text":": "},{"text":"Warning: ","color":"red","bold":"true"},{"text":"Please use guess 7.","color":"gold"}]}
execute @s[score_MMHcl_min=0,score_MMHcl=0,score_MMHgn_min=8,score_MMHgn=8] ~ ~ ~ tellraw @a[score_MMHrn_min=2,score_MMHrn=2] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"MMH","color":"red","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Mastermind Hell","color":"red"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 525124045"}},{"text":"]","color":"gray"},{"text":": "},{"text":"Warning: ","color":"red","bold":"true"},{"text":"Please use guess 8.","color":"gold"}]}
execute @s[score_MMHcl_min=0,score_MMHcl=0,score_MMHgn_min=9,score_MMHgn=9] ~ ~ ~ tellraw @a[score_MMHrn_min=2,score_MMHrn=2] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"MMH","color":"red","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Mastermind Hell","color":"red"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 525124045"}},{"text":"]","color":"gray"},{"text":": "},{"text":"Warning: ","color":"red","bold":"true"},{"text":"Please use guess 9.","color":"gold"}]}
execute @s[score_MMHcl_min=1,score_MMHcl=1] ~ ~ ~ function ego:mastermind_hell/select_player_for_guess_2
scoreboard players operation @s[score_MMHcl_min=2,score_MMHcl=2] MMHpl = @s MMHgn
scoreboard players operation @s[score_MMHcl_min=2,score_MMHcl=2] MMHpl *= -1 constants
scoreboard players remove @s[score_MMHcl_min=2,score_MMHcl=2,score_MMHca_min=0,score_MMHca=0] MMHpl 100
scoreboard players operation @a[score_MMHrn_min=2,score_MMHrn=2] MMHec = @s MMHpl
scoreboard players add @s[score_MMHcl_min=2,score_MMHcl=2] MMHgn 1
scoreboard players set @s MMHcl 0
