scoreboard players operation @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHGuess1] MMHca = @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHCorrect1] MMHca
scoreboard players operation @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHGuess2] MMHca = @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHCorrect2] MMHca
scoreboard players operation @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHGuess3] MMHca = @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHCorrect3] MMHca
scoreboard players operation @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHGuess4] MMHca = @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHCorrect4] MMHca
scoreboard players operation @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHGuess5] MMHca = @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHCorrect5] MMHca
scoreboard players operation @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHGuess6] MMHca = @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHCorrect6] MMHca
execute @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHGuess,score_MMHca_min=1,score_MMHca=1] ~ ~ ~ execute @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHGuess,rm=1,r=5,score_MMHbi_min=1,score_MMHbi=1] ~ ~ ~ scoreboard players add @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHWhite] MMHcl 1
execute @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHGuess,score_MMHca_min=1,score_MMHca=1,score_MMHbi_min=1,score_MMHbi=1] ~ ~ ~ scoreboard players add @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHRed] MMHcl 1
execute @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHGuess,score_MMHca_min=2,score_MMHca=2] ~ ~ ~ execute @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHGuess,rm=1,r=5,score_MMHbi_min=2,score_MMHbi=2] ~ ~ ~ scoreboard players add @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHWhite] MMHcl 1
execute @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHGuess,score_MMHca_min=2,score_MMHca=2,score_MMHbi_min=2,score_MMHbi=2] ~ ~ ~ scoreboard players add @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHRed] MMHcl 1
execute @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHGuess,score_MMHca_min=3,score_MMHca=3] ~ ~ ~ execute @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHGuess,rm=1,r=5,score_MMHbi_min=3,score_MMHbi=3] ~ ~ ~ scoreboard players add @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHWhite] MMHcl 1
execute @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHGuess,score_MMHca_min=3,score_MMHca=3,score_MMHbi_min=3,score_MMHbi=3] ~ ~ ~ scoreboard players add @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHRed] MMHcl 1
execute @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHGuess,score_MMHca_min=4,score_MMHca=4] ~ ~ ~ execute @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHGuess,rm=1,r=5,score_MMHbi_min=4,score_MMHbi=4] ~ ~ ~ scoreboard players add @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHWhite] MMHcl 1
execute @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHGuess,score_MMHca_min=4,score_MMHca=4,score_MMHbi_min=4,score_MMHbi=4] ~ ~ ~ scoreboard players add @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHRed] MMHcl 1
execute @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHGuess,score_MMHca_min=5,score_MMHca=5] ~ ~ ~ execute @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHGuess,rm=1,r=5,score_MMHbi_min=5,score_MMHbi=5] ~ ~ ~ scoreboard players add @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHWhite] MMHcl 1
execute @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHGuess,score_MMHca_min=5,score_MMHca=5,score_MMHbi_min=5,score_MMHbi=5] ~ ~ ~ scoreboard players add @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHRed] MMHcl 1
execute @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHGuess,score_MMHca_min=6,score_MMHca=6] ~ ~ ~ execute @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHGuess,rm=1,r=5,score_MMHbi_min=6,score_MMHbi=6] ~ ~ ~ scoreboard players add @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHWhite] MMHcl 1
execute @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHGuess,score_MMHca_min=6,score_MMHca=6,score_MMHbi_min=6,score_MMHbi=6] ~ ~ ~ scoreboard players add @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHRed] MMHcl 1
execute @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHGuess,score_MMHca_min=7,score_MMHca=7] ~ ~ ~ execute @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHGuess,rm=1,r=5,score_MMHbi_min=7,score_MMHbi=7] ~ ~ ~ scoreboard players add @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHWhite] MMHcl 1
execute @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHGuess,score_MMHca_min=7,score_MMHca=7,score_MMHbi_min=7,score_MMHbi=7] ~ ~ ~ scoreboard players add @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHRed] MMHcl 1
execute @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHGuess,score_MMHca_min=8,score_MMHca=8] ~ ~ ~ execute @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHGuess,rm=1,r=5,score_MMHbi_min=8,score_MMHbi=8] ~ ~ ~ scoreboard players add @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHWhite] MMHcl 1
execute @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHGuess,score_MMHca_min=8,score_MMHca=8,score_MMHbi_min=8,score_MMHbi=8] ~ ~ ~ scoreboard players add @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHRed] MMHcl 1
scoreboard players add @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHRed] MMHcl 0
scoreboard players add @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHWhite] MMHcl 0
setblock ~7 ~ ~ standing_sign 2 replace {Text1:"{\"text\":\"-=-\"}",Text2:"{\"text\":\"\",\"extra\":[{\"score\":{\"name\":\"@e[type=area_effect_cloud,tag=MMHRed]\",\"objective\":\"MMHcl\"}},{\"text\":\" red\"}]}",Text3:"{\"text\":\"\",\"extra\":[{\"score\":{\"name\":\"@e[type=area_effect_cloud,tag=MMHWhite]\",\"objective\":\"MMHcl\"}},{\"text\":\" white\"}]}",Text4:"{\"text\":\"-=-\"}"}
execute @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHRed,score_MMHcl_min=6,score_MMHcl=6] ~ ~ ~ setblock ~7 ~ ~ air 0
execute @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHRed,score_MMHcl_min=6,score_MMHcl=6] ~ ~ ~ setblock ~7 ~ ~ standing_sign 2 replace {Text1:"{\"text\":\"--=--\"}",Text2:"{\"text\":\"6 red\",\"bold\":\"true\"}",Text3:"{\"text\":\"Shhhh\",\"bold\":\"true\"}",Text4:"{\"text\":\"--=--\"}"}
execute @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHWhite,score_MMHcl_min=0,score_MMHcl=0] ~ ~ ~ execute @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHRed,score_MMHcl_min=1,score_MMHcl=5] ~ ~ ~ setblock ~7 ~ ~ air 0
execute @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHWhite,score_MMHcl_min=0,score_MMHcl=0] ~ ~ ~ execute @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHRed,score_MMHcl_min=1,score_MMHcl=5] ~ ~ ~ setblock ~7 ~ ~ standing_sign 2 replace {Text1:"{\"text\":\"-=-\"}",Text2:"{\"text\":\"\",\"extra\":[{\"score\":{\"name\":\"@e[type=area_effect_cloud,tag=MMHRed]\",\"objective\":\"MMHcl\"}},{\"text\":\" red\"}]}",Text3:"{\"text\":\"-=-\"}",Text4:"{\"text\":\"\"}"}
execute @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHWhite,score_MMHcl_min=1,score_MMHcl=6] ~ ~ ~ execute @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHRed,score_MMHcl_min=0,score_MMHcl=0] ~ ~ ~ setblock ~7 ~ ~ air 0
execute @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHWhite,score_MMHcl_min=1,score_MMHcl=6] ~ ~ ~ execute @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHRed,score_MMHcl_min=0,score_MMHcl=0] ~ ~ ~ setblock ~7 ~ ~ standing_sign 2 replace {Text1:"{\"text\":\"-=-\"}",Text2:"{\"text\":\"\",\"extra\":[{\"score\":{\"name\":\"@e[type=area_effect_cloud,tag=MMHWhite]\",\"objective\":\"MMHcl\"}},{\"text\":\" white\"}]}",Text3:"{\"text\":\"-=-\"}",Text4:"{\"text\":\"\"}"}
setblock ~ ~ ~ tripwire 0 replace stone_button
scoreboard players set @e[type=armor_stand,tag=MMHRoom1,score_MMHca_min=0,score_MMHca=0,score_MMHcl_min=1,score_MMHcl=1] MMHcl 2
execute @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHRed,score_MMHcl_min=6,score_MMHcl=6] ~ ~ ~ scoreboard players set @e[type=armor_stand,tag=MMHRoom1,score_MMHca_min=0,score_MMHca=0] MMHca 1
execute @e[score_MMHrn_min=1,score_MMHrn=1,tag=MMHRed,score_MMHcl_min=6,score_MMHcl=6] ~ ~ ~ fill ~ ~4 ~ ~ ~6 ~ sea_lantern 0 replace redstone_lamp
clone ~1 ~-1 ~ ~6 ~-1 ~ ~1 ~-3 ~
setblock ~ ~5 ~ redstone_block 0
