minecraft:tp @e[type=armor_stand,tag=MMHCorrect,score_MMHrn_min=1,score_MMHrn=4] ~-7 ~5 ~-20
minecraft:tp @e[type=armor_stand,tag=MMHCorrect,score_MMHrn_min=5,score_MMHrn=8] ~7 ~5 ~20
minecraft:tp @e[type=armor_stand,tag=MMHCorrect,tag=MMHCorrect1,score_MMHrn_min=1,score_MMHrn=4] ~0 ~ ~
minecraft:tp @e[type=armor_stand,tag=MMHCorrect,tag=MMHCorrect2,score_MMHrn_min=1,score_MMHrn=4] ~1 ~ ~
minecraft:tp @e[type=armor_stand,tag=MMHCorrect,tag=MMHCorrect3,score_MMHrn_min=1,score_MMHrn=4] ~2 ~ ~
minecraft:tp @e[type=armor_stand,tag=MMHCorrect,tag=MMHCorrect4,score_MMHrn_min=1,score_MMHrn=4] ~3 ~ ~
minecraft:tp @e[type=armor_stand,tag=MMHCorrect,tag=MMHCorrect5,score_MMHrn_min=1,score_MMHrn=4] ~4 ~ ~
minecraft:tp @e[type=armor_stand,tag=MMHCorrect,tag=MMHCorrect6,score_MMHrn_min=1,score_MMHrn=4] ~5 ~ ~
minecraft:tp @e[type=armor_stand,tag=MMHCorrect,tag=MMHCorrect1,score_MMHrn_min=5,score_MMHrn=8] ~0 ~ ~
minecraft:tp @e[type=armor_stand,tag=MMHCorrect,tag=MMHCorrect2,score_MMHrn_min=5,score_MMHrn=8] ~-1 ~ ~
minecraft:tp @e[type=armor_stand,tag=MMHCorrect,tag=MMHCorrect3,score_MMHrn_min=5,score_MMHrn=8] ~-2 ~ ~
minecraft:tp @e[type=armor_stand,tag=MMHCorrect,tag=MMHCorrect4,score_MMHrn_min=5,score_MMHrn=8] ~-3 ~ ~
minecraft:tp @e[type=armor_stand,tag=MMHCorrect,tag=MMHCorrect5,score_MMHrn_min=5,score_MMHrn=8] ~-4 ~ ~
minecraft:tp @e[type=armor_stand,tag=MMHCorrect,tag=MMHCorrect6,score_MMHrn_min=5,score_MMHrn=8] ~-5 ~ ~
