minecraft:tp @e[type=armor_stand,tag=MMCorrect,score_MMrn_min=1,score_MMrn=6] ~-5 ~5 ~-12
minecraft:tp @e[type=armor_stand,tag=MMCorrect,score_MMrn_min=7,score_MMrn=12] ~5 ~5 ~12
minecraft:tp @e[type=armor_stand,tag=MMCorrect,tag=MMCorrect1,score_MMrn_min=1,score_MMrn=6] ~0 ~ ~
minecraft:tp @e[type=armor_stand,tag=MMCorrect,tag=MMCorrect2,score_MMrn_min=1,score_MMrn=6] ~1 ~ ~
minecraft:tp @e[type=armor_stand,tag=MMCorrect,tag=MMCorrect3,score_MMrn_min=1,score_MMrn=6] ~2 ~ ~
minecraft:tp @e[type=armor_stand,tag=MMCorrect,tag=MMCorrect4,score_MMrn_min=1,score_MMrn=6] ~3 ~ ~
minecraft:tp @e[type=armor_stand,tag=MMCorrect,tag=MMCorrect1,score_MMrn_min=7,score_MMrn=12] ~0 ~ ~
minecraft:tp @e[type=armor_stand,tag=MMCorrect,tag=MMCorrect2,score_MMrn_min=7,score_MMrn=12] ~-1 ~ ~
minecraft:tp @e[type=armor_stand,tag=MMCorrect,tag=MMCorrect3,score_MMrn_min=7,score_MMrn=12] ~-2 ~ ~
minecraft:tp @e[type=armor_stand,tag=MMCorrect,tag=MMCorrect4,score_MMrn_min=7,score_MMrn=12] ~-3 ~ ~
