scoreboard players add @s NRcd 1
execute @s[score_NRcd_min=20,score_NRcd=20] ~ ~ ~ tellraw @a[score_gSA_min=1,score_gSA=1] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"NR","color":"red","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Nether Race","color":"red"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1061722156"}},{"text":"]","color":"gray"},{"text":": "},{"text":"5","color":"yellow","bold":"true"}]}
execute @s[score_NRcd_min=20,score_NRcd=20] ~ ~ ~ execute @a[score_gSA_min=1,score_gSA=1] ~ ~ ~ playsound minecraft:block.note.pling voice @a[c=1] ~ ~ ~ 0.5
execute @s[score_NRcd_min=40,score_NRcd=40] ~ ~ ~ tellraw @a[score_gSA_min=1,score_gSA=1] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"NR","color":"red","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Nether Race","color":"red"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1061722156"}},{"text":"]","color":"gray"},{"text":": "},{"text":"4","color":"yellow","bold":"true"}]}
execute @s[score_NRcd_min=40,score_NRcd=40] ~ ~ ~ execute @a[score_gSA_min=1,score_gSA=1] ~ ~ ~ playsound minecraft:block.note.pling voice @a[c=1] ~ ~ ~ 1
execute @s[score_NRcd_min=60,score_NRcd=60] ~ ~ ~ tellraw @a[score_gSA_min=1,score_gSA=1] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"NR","color":"red","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Nether Race","color":"red"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1061722156"}},{"text":"]","color":"gray"},{"text":": "},{"text":"3","color":"yellow","bold":"true"}]}
execute @s[score_NRcd_min=60,score_NRcd=60] ~ ~ ~ execute @a[score_gSA_min=1,score_gSA=1] ~ ~ ~ playsound minecraft:block.note.pling voice @a[c=1] ~ ~ ~ 1.5
execute @s[score_NRcd_min=80,score_NRcd=80] ~ ~ ~ tellraw @a[score_gSA_min=1,score_gSA=1] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"NR","color":"red","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Nether Race","color":"red"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1061722156"}},{"text":"]","color":"gray"},{"text":": "},{"text":"2","color":"yellow","bold":"true"}]}
execute @s[score_NRcd_min=80,score_NRcd=80] ~ ~ ~ execute @a[score_gSA_min=1,score_gSA=1] ~ ~ ~ playsound minecraft:block.note.pling voice @a[c=1] ~ ~ ~ 2
execute @s[score_NRcd_min=100,score_NRcd=100] ~ ~ ~ tellraw @a[score_gSA_min=1,score_gSA=1] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"NR","color":"red","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Nether Race","color":"red"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1061722156"}},{"text":"]","color":"gray"},{"text":": "},{"text":"1","color":"yellow","bold":"true"}]}
execute @s[score_NRcd_min=100,score_NRcd=100] ~ ~ ~ execute @a[score_gSA_min=1,score_gSA=1] ~ ~ ~ playsound minecraft:block.note.pling voice @a[c=1] ~ ~ ~ 2
execute @s[score_NRcd_min=120,score_NRcd=120] ~ ~ ~ execute @a[score_gSA_min=1,score_gSA=1] ~ ~ ~ playsound minecraft:entity.wither.death voice @a[c=1]
execute @s[score_NRcd_min=120,score_NRcd=120] ~ ~ ~ tellraw @a[score_gSA_min=1,score_gSA=1] {"text":"","extra":[{"text":"[","color":"gray"},{"text":"NR","color":"red","bold":"true","hoverEvent":{"action":"show_text","value":{"text":"Nether Race","color":"red"}},"clickEvent":{"action":"run_command","value":"/scoreboard players set @p FLtp 1061722156"}},{"text":"]","color":"gray"},{"text":": "},{"text":"GO!","color":"green","bold":"true"}]}
execute @s[score_NRcd_min=120,score_NRcd=120] ~ ~ ~ title @a[score_gSA_min=1,score_gSA=1] title {"text":"GO!","color":"green"}
execute @s[score_NRcd_min=120,score_NRcd=120] ~ ~ ~ fill 68 5 -100 68 5 -104 stonebrick 0 replace redstone_block 0
